---
- name: Start and enable containerd
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    enabled: true
    name: containerd
  listen: "restart containerd"

- name: Start and enable kubelet
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    enabled: true
    name: kubelet
  listen: "restart kubelet"
